spring.application.name=accompagnement_france_backend
server.port=8081
server.servlet.context-path=/api
cors.allowed-origins=http://localhost:4200,http://localhost:4201

spring.datasource.url=jdbc:postgresql://localhost:5432/accompagnement_france
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=
spring.datasource.password=

# JWT Security Configuration
application.security.jwt.secret-key=
application.security.jwt.expiration=1200000
application.security.jwt.refresh-token.expiration=604800000

# default admin creadentials :
admin_default_email=
admin_default_password=


app.security.cookie.secure=true
app.security.cookie.same-site=None
app.security.cookie.path=/api/auth


retention.retentionRuleAction=ANONYMIZE
retention.daysToRetainAfterClosure=90


# Brevo configuration (the email service)
brevo.api.key=
brevo.email.admin.email=
brevo.sender.email=
brevo.sender.name=Cabinet de conseil
